# Versi Python
runtime: python37

# Perangkat yang kita akan pakai, yaitu: F2
instance_class: F2

# Nama servis, ini yang pertama jadi harus default
service: default

handlers:
  # Directory untuk CSS
- url: /static
  static_dir: static

  # Penanganan URL selain untuk berkas-berkas statis.
- url: /.*
  script: auto
